2024-06-08 23:19:30,948 (PID 16699) [INFO] autoreload
Watching for file changes with StatReloader
2024-06-08 23:19:34,196 (PID 16699) [ERROR] log
Internal Server Error: /
Traceback (most recent call last):
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: puzzles_erratum

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/asgiref/sync.py", line 482, in thread_handler
    raise exc_info[1]
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/asgiref/sync.py", line 444, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/root/miniconda3/envs/gph/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/asgiref/sync.py", line 486, in thread_handler
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/www/wwwroot/ph.sapium.site/fduph24/puzzles/views.py", line 165, in index
    return render(request, 'home.html')
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/defaulttags.py", line 308, in render
    match = condition.eval(context)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/defaulttags.py", line 892, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/www/wwwroot/ph.sapium.site/fduph24/puzzles/context.py", line 30, in <lambda>
    return lambda: getattr(request.context, name)
  File "/www/wwwroot/ph.sapium.site/fduph24/puzzles/context.py", line 41, in fget
    self._cache[name] = fn(self)
  File "/www/wwwroot/ph.sapium.site/fduph24/puzzles/context.py", line 163, in errata_page_visible
    return self.is_superuser or any(erratum.updates_text for erratum in self.visible_errata)
  File "/www/wwwroot/ph.sapium.site/fduph24/puzzles/context.py", line 41, in fget
    self._cache[name] = fn(self)
  File "/www/wwwroot/ph.sapium.site/fduph24/puzzles/context.py", line 160, in visible_errata
    return models.Erratum.get_visible_errata(self)
  File "/www/wwwroot/ph.sapium.site/fduph24/puzzles/models.py", line 728, in get_visible_errata
    for erratum in Erratum.objects.select_related('puzzle').order_by('timestamp'):
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/root/miniconda3/envs/gph/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: puzzles_erratum
2024-06-08 23:19:34,203 (PID 16699) [ERROR] runserver
[35;1mHTTP GET / 500 [0.15, 127.0.0.1:44038][0m
2024-06-08 23:19:35,292 (PID 16699) [WARNING] log
Not Found: /favicon.ico
2024-06-08 23:19:35,293 (PID 16699) [WARNING] runserver
[33mHTTP GET /favicon.ico 404 [0.01, 127.0.0.1:44038][0m
2024-06-08 23:21:23,234 (PID 17456) [INFO] autoreload
Watching for file changes with StatReloader
2024-06-08 23:21:25,495 (PID 17456) [INFO] runserver
[mHTTP GET / 200 [0.03, 127.0.0.1:44186][0m
2024-06-08 23:21:25,573 (PID 17456) [INFO] runserver
[mHTTP GET /static/css/skeleton.css 200 [0.01, 127.0.0.1:44186][0m
2024-06-08 23:21:25,576 (PID 17456) [INFO] runserver
[mHTTP GET /static/css/base.css 200 [0.01, 127.0.0.1:44190][0m
2024-06-08 23:21:25,646 (PID 17456) [INFO] runserver
[mHTTP GET /static/js/notify.js 200 [0.00, 127.0.0.1:44186][0m
2024-06-08 23:21:25,707 (PID 17456) [INFO] runserver
[mHTTP GET /static/js/time.js 200 [0.00, 127.0.0.1:44190][0m
2024-06-08 23:21:25,798 (PID 17456) [INFO] runserver
[mHTTP GET /static/js/jquery.formset.js 200 [0.00, 127.0.0.1:44210][0m
2024-06-08 23:21:25,801 (PID 17456) [INFO] runserver
[mHTTP GET /static/js/sorttable.js 200 [0.00, 127.0.0.1:44212][0m
2024-06-08 23:21:25,807 (PID 17456) [INFO] runserver
[mHTTP GET /jsi18n/ 200 [0.01, 127.0.0.1:44208][0m
2024-06-08 23:21:25,809 (PID 17456) [INFO] runserver
[mHTTP GET /static/js/tray.js 200 [0.01, 127.0.0.1:44214][0m
2024-06-08 23:21:26,217 (PID 17456) [INFO] runserver
[mHTTP GET /static/images/favicon.ico 200 [0.00, 127.0.0.1:44214][0m
2024-06-08 23:21:59,550 (PID 17456) [INFO] runserver
[mHTTP GET /register 200 [0.03, 127.0.0.1:44214][0m
2024-06-08 23:22:35,551 (PID 17456) [INFO] runserver
[mHTTP POST /register 200 [0.03, 127.0.0.1:44214][0m
2024-06-08 23:23:17,951 (PID 17456) [INFO] runserver
[32mHTTP POST /register 302 [0.24, 127.0.0.1:44214][0m
2024-06-08 23:23:18,015 (PID 17456) [INFO] runserver
[mHTTP GET / 200 [0.02, 127.0.0.1:44214][0m
2024-06-08 23:23:18,183 (PID 17456) [INFO] runserver
[36mHTTP GET /static/css/base.css 304 [0.00, 127.0.0.1:44300][0m
2024-06-08 23:23:18,184 (PID 17456) [INFO] runserver
[36mHTTP GET /static/css/skeleton.css 304 [0.00, 127.0.0.1:44214][0m
2024-06-08 23:23:18,361 (PID 17456) [INFO] runserver
[36mHTTP GET /static/js/notify.js 304 [0.00, 127.0.0.1:44300][0m
2024-06-08 23:23:18,443 (PID 17456) [INFO] runserver
[36mHTTP GET /static/js/time.js 304 [0.00, 127.0.0.1:44372][0m
2024-06-08 23:23:18,444 (PID 17456) [INFO] runserver
[36mHTTP GET /static/js/jquery.formset.js 304 [0.00, 127.0.0.1:44374][0m
2024-06-08 23:23:18,445 (PID 17456) [INFO] runserver
[36mHTTP GET /static/js/sorttable.js 304 [0.00, 127.0.0.1:44376][0m
2024-06-08 23:23:18,483 (PID 17456) [INFO] runserver
[36mHTTP GET /static/js/tray.js 304 [0.00, 127.0.0.1:44380][0m
2024-06-08 23:23:18,640 (PID 17456) [INFO] runserver
WebSocket HANDSHAKING /ws/team [127.0.0.1:44386]
2024-06-08 23:23:18,646 (PID 17456) [INFO] runserver
WebSocket CONNECT /ws/team [127.0.0.1:44386]
2024-06-08 23:24:13,486 (PID 17456) [INFO] autoreload
/www/wwwroot/ph.sapium.site/fduph24/gph/settings/base.py changed, reloading.
2024-06-08 23:24:14,509 (PID 18496) [INFO] autoreload
Watching for file changes with StatReloader
2024-06-08 23:24:15,781 (PID 18496) [INFO] autoreload
/www/wwwroot/ph.sapium.site/fduph24/gph/settings/base.py changed, reloading.
2024-06-08 23:24:16,730 (PID 18534) [INFO] autoreload
Watching for file changes with StatReloader
